### PR TITLE
models changes in locally

### PR DESCRIPTION
**Pull request by shus0001**
Hi ,I tried to pull the updated folder through git bash it says i have some changes locally in visual studio .And suggested to commit to git ..here is code come in git bash 

and I haven't make any changes since last time in class . So i am committing request …..

shush@HP-Mobil-MFZ001 MINGW64 ~/Desktop/SOVA final version/SOVA (new-commit)
$ git pull origin master
From https://github.com/ivanspajic/SOVA
 * branch            master     -> FETCH_HEAD
Updating 4caac61..3272ef9
error: Your local changes to the following files would be overwritten by merge:
        Subproject2/0. Models/obj/0. Models.csproj.nuget.cache
        Subproject2/0. Models/obj/0. Models.csproj.nuget.dgspec.json
        Subproject2/0. Models/obj/0. Models.csproj.nuget.g.props
        Subproject2/0. Models/obj/Debug/netcoreapp3.0/0. Models.assets.cache
        Subproject2/0. Models/obj/project.assets.json
Please commit your changes or stash them before you merge.

### CODE REVIEW

**Comment by shrestaz** [comment]
1. from your git bash, do `git stash` from project folder. It'll ignore any changes that may have been made.
2. make sure you're on master branch: `git checkout master`
3. After that, do `git pull` from your master branch.
4. then create a new branch and implement your feature.

**Comment by shrestaz** [comment]
And issues like this is not fixed by a Pull Request so please close this when you've fixed it 😃

**Review by shrestaz — CHANGES_REQUESTED** [review]
And issues like this is not fixed by a Pull Request so please close this when you've fixed it 😃

**Comment by shus0001** [comment]
ok ,, i will try!

**Pull request closed without merging**
